subtask_b.4:
	gcc subtask_b.1.c -o subtask_b.1
	gcc subtask_b.2.c -o subtask_b.2
	gcc subtask_b.3.c -o subtask_b.3
	gcc subtask_b.4.c -o subtask_b.4
clean:
	rm -f *.o subtask_b.1 subtask_b.2 subtask_b.3 subtask_b.4